DROP VIEW IF EXISTS experiments;
CREATE VIEW experiments AS
select
    id,
    file,
    created,
    modified,
    patientId as patient_id,
    patientSiteId as patient_site_id,
    patientGenderAtBirth as patient_gender_at_birth,
    patientCountryOfBirth as patient_country_of_birth,
    patientAge as patient_age,
    patientBmi as patient_bmi,
    patientInjectingDrugUse as patient_injecting_drug_use,
    patientHomeless as patient_homeless,
    patientImprisoned as patient_imprisoned,
    patientSmoker as patient_smoker,
    patientDiabetic as patient_diabetic,
    patientHivStatus as patient_hiv_status,
    patientArt as patient_art,
    sampleLabId as sample_lab_id,
    sampleIsolateId as sample_isolate_id,
    sampleCollectionDate as sample_collection_date,
    sampleDateArrived as sample_date_arrived,
    sampleProspectiveIsolate as sample_prospective_isolate,
    sampleCountryIsolate as sample_country_isolate,
    sampleCityIsolate as sample_city_isolate,
    sampleLongitudeIsolate as sample_longitude,
    sampleLatitudeIsolate as sample_latitude,
    sampleAnatomicalOrigin as sample_anatomical_origin,
    sampleSmear as sample_smear,
    outcomeSputumSmearConversion as outcome_sputum_smear_conversion,
    outcomeSputumCultureConversion as outcome_sputum_culture_conversion,
    outcomeWhoOutcomeCategory  as outcome_who_category_outcome,
    outcomeDateOfDeath as outcome_date_of_death
from core_experiments
where deleted IS NULL;

DROP VIEW IF EXISTS deleted_experiments;
CREATE VIEW deleted_experiments AS
select
    id,
    file,
    created,
    modified,
    patientId as patient_id,
    patientSiteId as patient_site_id,
    patientGenderAtBirth as patient_gender_at_birth,
    patientCountryOfBirth as patient_country_of_birth,
    patientAge as patient_age,
    patientBmi as patient_bmi,
    patientInjectingDrugUse as patient_injecting_drug_use,
    patientHomeless as patient_homeless,
    patientImprisoned as patient_imprisoned,
    patientSmoker as patient_smoker,
    patientDiabetic as patient_diabetic,
    patientHivStatus as patient_hiv_status,
    patientArt as patient_art,
    sampleLabId as sample_lab_id,
    sampleIsolateId as sample_isolate_id,
    sampleCollectionDate as sample_collection_date,
    sampleDateArrived as sample_date_arrived,
    sampleProspectiveIsolate as sample_prospective_isolate,
    sampleCountryIsolate as sample_country_isolate,
    sampleCityIsolate as sample_city_isolate,
    sampleLongitudeIsolate as sample_longitude,
    sampleLatitudeIsolate as sample_latitude,
    sampleAnatomicalOrigin as sample_anatomical_origin,
    sampleSmear as sample_smear,
    outcomeSputumSmearConversion as outcome_sputum_smear_conversion,
    outcomeSputumCultureConversion as outcome_sputum_culture_conversion,
    outcomeWhoOutcomeCategory  as outcome_who_category_outcome,
    outcomeDateOfDeath as outcome_date_of_death
from core_experiments
where deleted IS NOT NULL;

DROP VIEW IF EXISTS experiment_predictor_results;
CREATE VIEW experiment_predictor_results AS
select
    e.id,
    r.received,
    r.kmer,
    r.mykrobePredictorVersion as mykrobe_predictor_version,
    r.mykrobeAtlasVersion as mykrobe_atlas_version,
    r.genotypeModel as genotype_model,
    r.externalId as external_id,
    r.isoniazid,
    r.kanamycin,
    r.ethambutol,
    r.streptomycin,
    r.capreomycin,
    r.ciprofloxacin,
    r.moxifloxacin,
    r.ofloxacin,
    r.pyrazinamide,
    r.amikacin,
    r.rifampicin,
    r.phyloGroup as phylo_group,
  	r.phyloGroupPercentCoverage as phylo_group_percent_coverage,
  	r.phyloGroupMedianDepth as phylo_group_median_depth,
	r.subComplex as sub_complex,
	r.subComplexPercentCoverage as sub_complex_percent_coverage,
	r.subComplexMedianDepth as sub_complex_median_depth,
	r.species as species,
	r.speciesPercentCoverage as species_percent_coverage,
	r.speciesMedianDepth as species_median_depth,
	r.lineage as lineage,
	r.lineagePercentCoverage as lineage_percent_coverage,
	r.lineageMedianDepth as lineage_median_depth,
    r.r,
    r.mdr,
    r.xdr,
    r.tdr,
    e.file,
    e.created,
    e.modified,
    e.patientId as patient_id,
    e.patientSiteId as patient_site_id,
    e.patientGenderAtBirth as patient_gender_at_birth,
    e.patientCountryOfBirth as patient_country_of_birth,
    e.patientAge as patient_age,
    e.patientBmi as patient_bmi,
    e.patientInjectingDrugUse as patient_injecting_drug_use,
    e.patientHomeless as patient_homeless,
    e.patientImprisoned as patient_imprisoned,
    e.patientSmoker as patient_smoker,
    e.patientDiabetic as patient_diabetic,
    e.patientHivStatus as patient_hiv_status,
    e.patientArt as patient_art,
    e.sampleLabId as sample_lab_id,
    e.sampleIsolateId as sample_isolate_id,
    e.sampleCollectionDate as sample_collection_date,
    e.sampleDateArrived as sample_date_arrived,
    e.sampleProspectiveIsolate as sample_prospective_isolate,
    e.sampleCountryIsolate as sample_country_isolate,
    e.sampleCityIsolate as sample_city_isolate,
    e.sampleLongitudeIsolate as sample_longitude,
    e.sampleLatitudeIsolate as sample_latitude,
    e.sampleAnatomicalOrigin as sample_anatomical_origin,
    e.sampleSmear as sample_smear,
    e.outcomeSputumSmearConversion as outcome_sputum_smear_conversion,
    e.outcomeSputumCultureConversion as outcome_sputum_culture_conversion,
    e.outcomeWhoOutcomeCategory  as outcome_who_category_outcome,
    e.outcomeDateOfDeath as outcome_date_of_death
from core_experiments e, core_predictor_result r
where r.experimentId = e.id
AND deleted IS NULL;